from __future__ import annotations

import json
from pathlib import Path

from build_mizo_stemmer_wordlist import build as build_wordlist
from corpus_stemming import ClarifiedSuffixStemmer, RepeatedSuffixStemmer, SuffixStemmer, evaluate_annotations


def build(root):
    stored_wordlist = json.loads((root / 'results/corpus/mizo-stemmer-auxiliary-wordlist.json').read_text(encoding='utf-8'))
    if stored_wordlist != build_wordlist(root):
        raise ValueError('Stemmer word list differs from auxiliary-only reconstruction')
    evaluation = evaluate_annotations(root / 'corpus/annotations/stemmer-production.reviewed.json', root / 'configs/stemming_production.json')
    evaluation['interpretation'] = 'Agreement on the fixed reviewed sample. Independent held-out accuracy was not estimated.'
    evaluation['execution_policy'] = json.loads((root / 'configs/mizo_stemmer_execution.json').read_text(encoding='utf-8'))
    specification = json.loads((root / 'resources/stemmers/lus-production.reviewed.json').read_text(encoding='utf-8'))
    old = SuffixStemmer(specification['rules'])
    new = ClarifiedSuffixStemmer(specification['rules'])
    previous = RepeatedSuffixStemmer(specification['rules'], set(stored_wordlist['tokens']), {'in', 'nain'})
    changed = [{'token': token, 'single_pass': old.stem(token), 'repeated': new.stem(token)} for token in stored_wordlist['tokens'] if old.stem(token) != new.stem(token)]
    evaluation['wordlist_token_count'] = stored_wordlist['token_count']
    evaluation['wordlist_document_count'] = stored_wordlist['document_count']
    evaluation['auxiliary_type_output_changes'] = len(changed)
    evaluation['output_change_examples'] = changed[:20]
    evaluation['clarification_type_output_changes'] = sum(previous.stem(token) != new.stem(token) for token in stored_wordlist['tokens'])
    evaluation['worked_examples'] = [{'token': token, 'output': new.stem(token), 'expected': expected} for token, expected in
                                    [('ṭawngṭainaahte', 'ṭawngṭai'), ('khawpuite', 'khawpui'), ('thlahte', 'thlah'), ('rorêltuten', 'rorêl')]]
    if any(item['output'] != item['expected'] for item in evaluation['worked_examples']):
        raise ValueError('Clarified worked example differs')
    return evaluation


def markdown(result):
    rows = []
    for language, label in [('en', 'English'), ('lus', 'Mizo')]:
        values = result['by_language'][language]
        rows.append(f"| {label} | {values['correct_count']} | {values['item_count']} | {values['accuracy']:.1%} |")
    mismatches = [f"| {item['language']} | {item['token']} | {item['predicted_stem']} | {item['expected_stem']} |" for item in result['items'] if not item['correct']]
    return '\n'.join([
        '# Stemming', '',
        'The execution policy used the reviewed suffix inventory and reviewer priorities. Rules were repeated until no permitted rule applied. Every rule shortened the token. Exceptions were tested against the current form and blocked only their own rule. Lower-priority rules remained eligible.', '',
        'The reviewer clarified the procedure on 7 October 2026. Corpus occurrence was excluded from rule eligibility. NFC-normalised letters were counted. Combining marks did not add letters.', '',
        'The accepted rule inventory excluded single-letter a and n removal and awm removal. Forms requiring those operations retained their unresolved evaluation disagreements. Expected stems were preserved. Annotation-specific exceptions and English corrections were not added.', '',
        '| Language | Matched | Annotated | Agreement |', '|---|---:|---:|---:|', *rows, '',
        result['interpretation'], '',
        '| Language | Token | Output | Expected stem |', '|---|---|---|---|', *mismatches, '',
        f"The execution change affected {result['auxiliary_type_output_changes']} attested auxiliary word types compared with the single-pass rules.", '',
        f"The clarification changed {result['clarification_type_output_changes']} auxiliary word types compared with the previous guarded procedure.", '',
        'All values were generated by scripts/analyse_stemmer_execution.py.', '',
    ])


def main():
    root = Path(__file__).resolve().parents[1]
    result = build(root)
    (root / 'results/corpus/stemmer-execution-evaluation.json').write_text(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + '\n', encoding='utf-8')
    (root / 'docs/stemmer-execution.md').write_text(markdown(result), encoding='utf-8')
    print(markdown(result))


if __name__ == '__main__':
    main()
