from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def build(root: Path, config_path: Path) -> str:
    config = load(config_path)
    if config.get("config_version") != "1.0.0":
        raise ValueError("Unsupported config_version")
    reviewer = config["reviewer"]
    resources = []
    for relative in config["review_scope"]:
        payload = load(root / relative)
        if "entries" in payload:
            pending = sum(item["decision"] == "pending" for item in payload["entries"])
            detail = f"{pending} pending token decisions"
        elif "rules" in payload:
            detail = f"{len(payload['rules'])} recorded rules"
        else:
            detail = f"{len(payload.get('items', []))} annotated items"
        resources.append((relative, payload["status"], detail))
    rows = "\n".join(
        f"| `{relative}` | {status} | {detail} |"
        for relative, status, detail in resources
    )
    return f"""# Linguistic review

Reviewer: {reviewer['name']}

Role: {reviewer['role']}

Qualification: {reviewer['qualification']}

Assignment date: {config['assigned_at']}

## Materials

| File | Status | Work remaining |
|---|---|---|
{rows}

## Procedure

Every stopword candidate requires `exclude_from_index` or `retain`. The basis should record the linguistic reason for the decision. Content words, names, and ambiguous forms should be retained unless the reviewer records a reason for exclusion.

The English stemmer review should confirm the Snowball English algorithm for this condition. The Mizo specification requires ordered suffix rules, minimum remaining letter counts, exceptions, and a basis for each rule.

The annotation sample requires expected stems for English and Mizo tokens. It should cover frequent and infrequent forms, unchanged forms, suffix cases, and exceptions.

Completion requires the reviewer name, completion date, approved status, and no pending decisions. The production builders and validators can then run.

This document was generated by `scripts/prepare_linguistic_review.py`.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare the assigned linguistic review record.")
    parser.add_argument("--config", type=Path, default=Path("configs/linguistic_review.json"))
    parser.add_argument("--output", type=Path, default=Path("docs/linguistic-review.md"))
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    document = build(root, root / args.config)
    output = root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(document, encoding="utf-8")
    print("Prepared linguistic review assignment")


if __name__ == "__main__":
    main()
